# Generated by Django 5.0.3 on 2024-04-07 23:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedbackApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='admin',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='admin',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='UID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='DateOfAdmission',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='DateOfGraduation',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='RollNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='DateOfJoining',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='UID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
